name: Publish Python Package to TestPyPI

on:
  push:
    branches: [ master ]  # or any branch you want to trigger the action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Increment version
      run: |
        current_version=$(grep -oP "(?<=version=')[^']*" setup.py)
        new_version=$(python -c "v='$current_version'.split('.'); v[-1]=str(int(v[-1])+1); print('.'.join(v))")
        sed -i "s/version='$current_version'/version='$new_version'/" setup.py
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository testpypi dist/*